--------------------------------------------------------
--  File created - Saturday-January-09-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence ACCOUNTSEQUENCE
--------------------------------------------------------

   CREATE SEQUENCE  "SHEETAPP"."ACCOUNTSEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 5 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence GANRESEQUENCE
--------------------------------------------------------

   CREATE SEQUENCE  "SHEETAPP"."GANRESEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SHEETSEQUENCE
--------------------------------------------------------

   CREATE SEQUENCE  "SHEETAPP"."SHEETSEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table ACCOUNTS
--------------------------------------------------------

  CREATE TABLE "SHEETAPP"."ACCOUNTS" 
   (	"USERID" NUMBER(7,0), 
	"USERNAME" VARCHAR2(20 BYTE), 
	"USERPASSWORD" VARCHAR2(20 BYTE), 
	"ACTIVEFLAG" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GANRES
--------------------------------------------------------

  CREATE TABLE "SHEETAPP"."GANRES" 
   (	"GANREID" NUMBER, 
	"GANRENAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SHEETS
--------------------------------------------------------

  CREATE TABLE "SHEETAPP"."SHEETS" 
   (	"SHEETID" NUMBER, 
	"SHEETNAME" VARCHAR2(50 BYTE), 
	"SHEET" "XMLTYPE", 
	"USERID" NUMBER, 
	"GANREID" NUMBER, 
	"DESCRIPTION" VARCHAR2(250 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 XMLTYPE COLUMN "SHEET" STORE AS BASICFILE BINARY XML (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ALLOW NONSCHEMA DISALLOW ANYSCHEMA ;
--------------------------------------------------------
--  DDL for Table XMLSTUF
--------------------------------------------------------

  CREATE TABLE "SHEETAPP"."XMLSTUF" 
   (	"XMLCOL" "XMLTYPE"
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 XMLTYPE COLUMN "XMLCOL" STORE AS BASICFILE BINARY XML (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ALLOW NONSCHEMA DISALLOW ANYSCHEMA ;
REM INSERTING into SHEETAPP.ACCOUNTS
SET DEFINE OFF;
Insert into SHEETAPP.ACCOUNTS (USERID,USERNAME,USERPASSWORD,ACTIVEFLAG) values (2,'vva','ase',1);
Insert into SHEETAPP.ACCOUNTS (USERID,USERNAME,USERPASSWORD,ACTIVEFLAG) values (1,'Tara','Tocilarilor',1);
Insert into SHEETAPP.ACCOUNTS (USERID,USERNAME,USERPASSWORD,ACTIVEFLAG) values (3,'1asd','aaw',0);
Insert into SHEETAPP.ACCOUNTS (USERID,USERNAME,USERPASSWORD,ACTIVEFLAG) values (4,'aas','ssdqwe',0);
REM INSERTING into SHEETAPP.GANRES
SET DEFINE OFF;
Insert into SHEETAPP.GANRES (GANREID,GANRENAME) values (1,'Something');
REM INSERTING into SHEETAPP.SHEETS
SET DEFINE OFF;
Insert into SHEETAPP.SHEETS (SHEETID,SHEETNAME,SHEET,USERID,GANREID,DESCRIPTION) values (1,'BlaSomething','<keyplay version1="4" version2="0" version3="0">
   <score title="This File Was Saved Using APT Version 4" copyright=" " artist="To access the music, please Download your FREE copy now, at www.ambrosepianotabs.com">
      <preferences fontsize="53" showtitle="1" showartist="1" tempo="120" zoom="100" colourmode="0"/>
   </score>
   <midi ppq="8"/>
</keyplay>',1,1,'BLAblablablaBLA');
REM INSERTING into SHEETAPP.XMLSTUF
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index SYS_C007000
--------------------------------------------------------

  CREATE UNIQUE INDEX "SHEETAPP"."SYS_C007000" ON "SHEETAPP"."ACCOUNTS" ("USERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007003
--------------------------------------------------------

  CREATE UNIQUE INDEX "SHEETAPP"."SYS_C007003" ON "SHEETAPP"."GANRES" ("GANREID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007015
--------------------------------------------------------

  CREATE UNIQUE INDEX "SHEETAPP"."SYS_C007015" ON "SHEETAPP"."SHEETS" ("SHEETID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ACCOUNTS
--------------------------------------------------------

  ALTER TABLE "SHEETAPP"."ACCOUNTS" ADD PRIMARY KEY ("USERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SHEETAPP"."ACCOUNTS" MODIFY ("USERPASSWORD" NOT NULL ENABLE);
  ALTER TABLE "SHEETAPP"."ACCOUNTS" MODIFY ("USERNAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GANRES
--------------------------------------------------------

  ALTER TABLE "SHEETAPP"."GANRES" ADD PRIMARY KEY ("GANREID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SHEETAPP"."GANRES" MODIFY ("GANRENAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SHEETS
--------------------------------------------------------

  ALTER TABLE "SHEETAPP"."SHEETS" ADD PRIMARY KEY ("SHEETID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SHEETAPP"."SHEETS" MODIFY ("GANREID" NOT NULL ENABLE);
  ALTER TABLE "SHEETAPP"."SHEETS" MODIFY ("USERID" NOT NULL ENABLE);
  ALTER TABLE "SHEETAPP"."SHEETS" MODIFY ("SHEETNAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table SHEETS
--------------------------------------------------------

  ALTER TABLE "SHEETAPP"."SHEETS" ADD FOREIGN KEY ("USERID")
	  REFERENCES "SHEETAPP"."ACCOUNTS" ("USERID") ENABLE;
  ALTER TABLE "SHEETAPP"."SHEETS" ADD FOREIGN KEY ("GANREID")
	  REFERENCES "SHEETAPP"."GANRES" ("GANREID") ENABLE;
--------------------------------------------------------
--  DDL for Trigger ACCOUNT_ID_TRIG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SHEETAPP"."ACCOUNT_ID_TRIG" 
BEFORE INSERT ON accounts

FOR EACH ROW

BEGIN
  SELECT accountsequence.NEXTVAL
  INTO   :new.userid
  FROM   dual;
END;
/
ALTER TRIGGER "SHEETAPP"."ACCOUNT_ID_TRIG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger GANREIDTRIGGER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SHEETAPP"."GANREIDTRIGGER" 
before INSERT ON ganres

FOR EACH ROW

BEGIN
  SELECT ganresequence.NEXTVAL
  INTO   :new.ganreid
  FROM   dual;
END;
/
ALTER TRIGGER "SHEETAPP"."GANREIDTRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SHEETIDTRIGGER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SHEETAPP"."SHEETIDTRIGGER" 
before INSERT ON sheets

FOR EACH ROW

BEGIN
  SELECT sheetsequence.NEXTVAL
  INTO   :new.sheetid
  FROM   dual;
END;
/
ALTER TRIGGER "SHEETAPP"."SHEETIDTRIGGER" ENABLE;
